[params.profileMode]
  enabled = true
  title = "Nagendra Gurram"
  subtitle = "Exploring AI Infrastructure, Cybersecurity, and Agentic Systems."
  imageUrl = "img/profile.jpg"
  imageWidth = 150
  imageHeight = 150
  imageTitle = "Nagendra Gurram"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/nagendra-kumar-gurram"
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/nagendra-gurram"
